export const TEXTS_FETCH_REQUEST = 'TEXTS_FETCH_REQUEST'
export const TEXTS_FETCH_FAILURE = 'TEXTS_FETCH_FAILURE'
export const TEXTS_FETCH_SUCCESS = 'TEXTS_FETCH_SUCCESS'

export const TEXTS_SHOW_REQUEST = 'TEXTS_SHOW_REQUEST'
export const TEXTS_SHOW_FAILURE = 'TEXTS_SHOW_FAILURE'
export const TEXTS_SHOW_SUCCESS = 'TEXTS_SHOW_SUCCESS'

export const START_GAME_REQUEST = 'START_GAME_REQUEST'
export const START_GAME_FAILURE = 'START_GAME_FAILURE'
export const START_GAME_SUCCESS = 'START_GAME_SUCCESS'

export const RESTART_GAME = 'RESTART_GAME'

export const GUESS_LETTER = 'GUESS_LETTER'
export const GUESS_LETTER_FAILURE = 'GUESS_LETTER_FAILURE'
export const GUESS_LETTER_SUCCESS = 'GUESS_LETTER_SUCCESS'
