export const TEXTS_FETCH_REQUEST = 'TEXTS_FETCH_REQUEST'
export const TEXTS_FETCH_FAILURE = 'TEXTS_FETCH_FAILURE'
export const TEXTS_FETCH_SUCCESS = 'TEXTS_FETCH_SUCCESS'

export const TEXTS_SHOW_REQUEST = 'TEXTS_SHOW_REQUEST'
export const TEXTS_SHOW_FAILURE = 'TEXTS_SHOW_FAILURE'
export const TEXTS_SHOW_SUCCESS = 'TEXTS_SHOW_SUCCESS'
